background = "#000000"
foreground = "#F5E1A4"
cursor-color = "#FFB938"
selection-background = "#4A3818"
selection-foreground = "#F5E1A4"
palette = 0=#000000
palette = 1=#F4C430
palette = 2=#8B6F2B
palette = 3=#E8A33D
palette = 4=#8B6F2B
palette = 5=#B0741F
palette = 6=#8B6F2B
palette = 7=#F5E1A4
palette = 8=#4A3818
palette = 9=#FFB938
palette = 10=#8B6F2B
palette = 11=#F4C430
palette = 12=#8B6F2B
palette = 13=#E8A33D
palette = 14=#8B6F2B
palette = 15=#F5E1A4
